language: python

dist: xenial   # required for Python >= 3.7

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "nightly"

matrix:
  allow_failures:
    - python: 'nightly'

install:
  - pip install -e.
  - pip install pytest

script: pytest

sudo: false
